/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nutriapp;

import Clases.CConexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.CallableStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author SYSTEMarket
 */
public class Ingreso extends javax.swing.JFrame {

    int xMouse, yMouse;

    int codigo;
    String nombreAlumnos;
    String apellidosAlumnos;
    
    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombreAlumnos() {
        return nombreAlumnos;
    }

    public void setNombreAlumnos(String nombreAlumnos) {
        this.nombreAlumnos = nombreAlumnos;
    }

    public String getApellidosAlumnos() {
        return apellidosAlumnos;
    }

    public void setApellidosAlumnos(String apellidosAlumnos) {
        this.apellidosAlumnos = apellidosAlumnos;
    }
    public void InsertarAlumno(JTextField usuario, JPasswordField clave){
        setNombreAlumnos(txtuser.getText());
        String sacarclave = String.valueOf(txtclave.getPassword());
        setApellidosAlumnos(sacarclave);

        CConexion objetoConexion = new CConexion();
        
        String consulta=("insert into Usuarios(ingresoUsuario,ingresoContra) values(?,?);");
        
        try{
            CallableStatement cs = objetoConexion.estableceConexion().prepareCall(consulta);
            
            cs.setString(1,getNombreAlumnos());
            cs.setString(2,getApellidosAlumnos());
            
            cs.execute();
            
            JOptionPane.showMessageDialog(null,"Se ha registrado correctamente, inicie sesión");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"A ocurrido iun error"+e.toString());

        }
    }
    
    public Ingreso() {
        initComponents();
       ImageIcon logoap= new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/LOGOAPP.png")));
       Image img1=logoap.getImage();
       Image img2=img1.getScaledInstance(nombreapp.getWidth(),nombreapp.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon i=new ImageIcon(img2);
       nombreapp.setIcon(i);

       logo.setIcon(new ImageIcon(getClass().getResource("/imagenes/fondo2.png")));
       SALUD.setIcon(new ImageIcon(getClass().getResource("/imagenes/SALUDPUBLICA.png")));
       FIE.setIcon(new ImageIcon(getClass().getResource("/imagenes/FIE.png")));
       logoemb1.setIcon(new ImageIcon(getClass().getResource("/imagenes/EMBSLogo.png")));
       ESPOCH.setIcon(new ImageIcon(getClass().getResource("/imagenes/ESPOCH.png")));

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        nombreapp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logoemb = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        cerrarbotn = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        clave = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtclave = new javax.swing.JPasswordField();
        botoningresar = new javax.swing.JPanel();
        textoingresar = new javax.swing.JLabel();
        FIE = new javax.swing.JLabel();
        botonregistrar1 = new javax.swing.JPanel();
        textoregistrar1 = new javax.swing.JLabel();
        logoemb1 = new javax.swing.JLabel();
        ESPOCH = new javax.swing.JLabel();
        SALUD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreapp.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        nombreapp.setText("jLabel2");
        fondo.add(nombreapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 170, 170));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("jLabel1");
        fondo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 200, 480));
        fondo.add(logoemb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 250, 70));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        cerrarbotn.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarbotnLayout = new javax.swing.GroupLayout(cerrarbotn);
        cerrarbotn.setLayout(cerrarbotnLayout);
        cerrarbotnLayout.setHorizontalGroup(
            cerrarbotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarbotnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cerrarbotnLayout.setVerticalGroup(
            cerrarbotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarbotnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NAME.setFont(new java.awt.Font("RomanD", 1, 18)); // NOI18N
        NAME.setText("NOMBRE DE LA APP");
        NAME.setToolTipText("");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(cerrarbotn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarbotn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        titulo.setText("INICIAR SESIÓN");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        usuario.setText("USUARIO");
        fondo.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtuser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su correo electrónico");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        fondo.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 450, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 430, -1));

        clave.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        clave.setText("CONTRASEÑA");
        fondo.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 430, -1));

        txtclave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtclave.setForeground(new java.awt.Color(204, 204, 204));
        txtclave.setText("********");
        txtclave.setBorder(null);
        txtclave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtclaveMousePressed(evt);
            }
        });
        fondo.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 430, -1));

        botoningresar.setBackground(new java.awt.Color(125, 175, 132));
        botoningresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botoningresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoningresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botoningresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoningresarMouseExited(evt);
            }
        });

        textoingresar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        textoingresar.setForeground(new java.awt.Color(255, 255, 255));
        textoingresar.setText("INGRESAR");

        javax.swing.GroupLayout botoningresarLayout = new javax.swing.GroupLayout(botoningresar);
        botoningresar.setLayout(botoningresarLayout);
        botoningresarLayout.setHorizontalGroup(
            botoningresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoningresarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textoingresar)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        botoningresarLayout.setVerticalGroup(
            botoningresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoningresarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoingresar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        fondo.add(botoningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 160, 50));

        FIE.setText("jLabel1");
        fondo.add(FIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 110, 50));

        botonregistrar1.setBackground(new java.awt.Color(125, 175, 132));
        botonregistrar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonregistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonregistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonregistrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonregistrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonregistrar1MouseExited(evt);
            }
        });

        textoregistrar1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        textoregistrar1.setForeground(new java.awt.Color(255, 255, 255));
        textoregistrar1.setText("REGISTRAR");

        javax.swing.GroupLayout botonregistrar1Layout = new javax.swing.GroupLayout(botonregistrar1);
        botonregistrar1.setLayout(botonregistrar1Layout);
        botonregistrar1Layout.setHorizontalGroup(
            botonregistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonregistrar1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textoregistrar1)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        botonregistrar1Layout.setVerticalGroup(
            botonregistrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonregistrar1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoregistrar1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        fondo.add(botonregistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));
        fondo.add(logoemb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 250, 70));

        ESPOCH.setText("jLabel1");
        fondo.add(ESPOCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 70));

        SALUD.setText("jLabel1");
        fondo.add(SALUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        cerrarbotn.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        cerrarbotn.setBackground(Color.white);
        exit.setForeground(Color.black);
    }//GEN-LAST:event_exitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if (txtuser.getText().equals("Ingrese su correo electrónico")) {
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtclave.getPassword()).isEmpty()) {
            txtclave.setText("********");
            txtclave.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtclaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtclaveMousePressed
if (String.valueOf(txtclave.getPassword()).equals("********")) {
            txtclave.setText("");
            txtclave.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()) {
            txtuser.setText("Ingrese su correo electrónico");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtclaveMousePressed

    private void botoningresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseEntered
        botoningresar.setBackground(new Color(82, 115, 80));
    }//GEN-LAST:event_botoningresarMouseEntered

    private void botoningresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseExited
        botoningresar.setBackground(new Color(125,175,132));
    }//GEN-LAST:event_botoningresarMouseExited

    private void botoningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoningresarMouseClicked
        Clases.Clogin objetoLogin = new Clases.Clogin();
        objetoLogin.validaUsuario(txtuser,txtclave);
        this.dispose();
        
    }//GEN-LAST:event_botoningresarMouseClicked

    private void botonregistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonregistrar1MouseClicked
        InsertarAlumno(txtuser,txtclave);
        
    }//GEN-LAST:event_botonregistrar1MouseClicked

    private void botonregistrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonregistrar1MouseEntered
        botonregistrar1.setBackground(new Color(82, 115, 80));
    }//GEN-LAST:event_botonregistrar1MouseEntered

    private void botonregistrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonregistrar1MouseExited
        botonregistrar1.setBackground(new Color(125,175,132));
    }//GEN-LAST:event_botonregistrar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ingreso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ESPOCH;
    private javax.swing.JLabel FIE;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel SALUD;
    private javax.swing.JPanel botoningresar;
    private javax.swing.JPanel botonregistrar1;
    private javax.swing.JPanel cerrarbotn;
    private javax.swing.JLabel clave;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoemb;
    private javax.swing.JLabel logoemb1;
    private javax.swing.JLabel nombreapp;
    private javax.swing.JLabel textoingresar;
    private javax.swing.JLabel textoregistrar1;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
